name: 'Run unit tests on push'
on: ['push']
jobs:
  unit-test:
    name: unit-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout github repo
        uses: actions/checkout@v4
      - name: Print message
        run: echo "Testing started"
      - name: Install packages
        run: npm install
      - name: Run unit test
        run: npm test
